// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkTeaMe.Repositories.Models;

public partial class ProductSize
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int SizeId { get; set; }

    public decimal Price { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductCombo> ProductCombos { get; set; } = new List<ProductCombo>();

    public virtual Size Size { get; set; }
}